# action.yml
name: 'Deploy Content'
description: 'Deploys content'
inputs:
  unit_name: ${{ github.repository.name }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.unit_name }}
    # - ${{ secrets.API_ROOT }}