# action.yml
name: 'Deploy Content'
description: 'Deploys content'
inputs:
  unit_name:
    description: Name of unit
    required: false
    default: ${{ github.repository }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.unit_name }}
    # - ${{ secrets.API_ROOT }}